import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import { auth } from './lib/auth';
import { headers } from 'next/headers';
import { CommerceContextProvider } from './lib/context/CommerceContext';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({ headers: await headers() });

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[70rem] mx-auto flex flex-col min-h-screen`}
      >
        <CommerceContextProvider>
          <Navbar session={session} />
          <div className="flex-grow h-full">{children}</div>
        </CommerceContextProvider>
        <Footer />
      </body>
    </html>
  );
}
